keycloak:
  url:
  username: {}
  password: {}
resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 100m
    memory: 512Mi
operatorImage: ghcr.io/rightcrowd/keycloak-realm-operator:0.0.18
genericCrds:
  - kind: KeycloakClientScope
    plural: keycloakclientscopes
    singular: keycloakclientscope
    short: kccs
    group: k8s.rightcrowd.com
    version: v1alpha1
  - kind: KeycloakGroup
    plural: keycloakgroups
    singular: keycloakgroup
    short: kcgp
    group: k8s.rightcrowd.com
    version: v1alpha1
