keycloak:
  url:
  username: {}
  password: {}
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 256Mi
operatorImage: ghcr.io/rightcrowd/keycloak-realm-operator:{{ .Chart.AppVersion }}
