keycloak:
  url:
  username: {}
  password: {}
resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 100m
    memory: 512Mi
operatorImage: ghcr.io/rightcrowd/keycloak-realm-operator:0.0.14