apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakclientcredentials.k8s.rightcrowd.com
spec:
  group: k8s.rightcrowd.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetSecretName:
                  type: string
                realm:
                  type: string
                clientId:
                  type: string
                fallbackStrategy:
                  type: string
                  enum:
                    - "skip"
                    - "error"
                targetSecretTemplate:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      template:
                        type: string
              required:
                - targetSecretName
            status:
              type: object
              properties:
                state:
                  type: string
                  enum:
                   - "not-synced"
                   - "out-of-sync"
                   - "syncing"
                   - "synced"
                   - "failed"
                  default: "not-synced"
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: TargetSecretName
          type: string
          description: The name of the realm
          jsonPath: .spec.targetSecretName
        - name: State
          type: string
          description: The state of the CR
          jsonPath: .status.state
  scope: Namespaced
  names:
    plural: keycloakclientcredentials
    singular: keycloakclientcredential
    kind: KeycloakClientCredential
    shortNames:
    - kccc
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
