{{- range $i, $value := .Values.genericCrds }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: {{ $value.value.plural }}.{{ $value.group }}
spec:
  group: {{ $value.group }}
  versions:
    - name: {{ $value.version }}
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                realm:
                  type: string
                id:
                  type: string
                prune:
                  type: boolean
                  default: false
                  description: Whether or not to delete the resource in Keycloak when the CR is deleted
                claimClient:
                  type: boolean
                  default: false
                  description: Whether or not to claim management of the resource if it already exists in Keycloak when the CR is created
                representation:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  description: Resource representation following the Keycloak spec
              required:
                - realm
                - id
            status:
              type: object
              properties:
                state:
                  type: string
                  enum:
                   - "not-synced"
                   - "syncing"
                   - "synced"
                   - "failed"
                  default: "not-synced"
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Realm
          type: string
          description: The id of the realm
          jsonPath: .spec.realm
        - name: Id
          type: string
          description: The id of the resource
          jsonPath: .spec.id
        - name: State
          type: string
          description: The state of the CR
          jsonPath: .status.state
  # either Namespaced or Cluster
  scope: Cluster
  names:
    plural: {{ $value.plural }}
    singular: {{ $value.singular }}
    kind: {{ $value.kind }}
    shortNames:
    - {{ $value.short }}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
{{- end }}