apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: managedkeycloakrealms.k8s.rightcrowd.com
spec:
  group: k8s.rightcrowd.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                realmId:
                  type: string
                displayName:
                  type: string
                pruneRealm:
                  type: boolean
                claimRealm:
                  type: boolean
                # Any value, should match RealmRepresentation
                representation:
                  type: object
                  additionalProperties: true
              required:
                - realmId
            status:
              type: object
              properties:
                state:
                  type: string
                  enum:
                   - "not-synced"
                   - "syncing"
                   - "synced"
                   - "failed"
                  default: "not-synced"
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: RealmName
          type: string
          description: The name of the realm
          jsonPath: .spec.realmName
        - name: State
          type: string
          description: The state of the CR
          jsonPath: .status.state
  # either Namespaced or Cluster
  scope: Cluster
  names:
    plural: managedkeycloakrealms
    singular: managedkeycloakrealm
    kind: ManagedKeycloakRealm
    shortNames:
    - mkcr
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
