apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keycloakusers.k8s.rightcrowd.com
spec:
  group: k8s.rightcrowd.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                realm:
                  type: string
                email:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
                username:
                  type: string
                prune:
                  type: boolean
                  default: false
                  description: Whether or not to delete the resource in Keycloak when the CR is deleted
                claim:
                  type: boolean
                  default: false
                  description: Whether or not to claim management of the resource if it already exists in Keycloak when the CR is created
                recreateOnClaim:
                  type: boolean
                  default: false
                  description: If enabled, the Keycloak resource will be deleted and recreated instead of simply being claimed
                representation:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  description: Resource representation following the Keycloak spec
              required:
                - email
            status:
              type: object
              properties:
                state:
                  type: string
                  enum:
                   - "not-synced"
                   - "syncing"
                   - "synced"
                   - "failed"
                  default: "not-synced"
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: email
          type: string
          description: The users email
          jsonPath: .spec.email
        - name: State
          type: string
          description: The state of the CR
          jsonPath: .status.state
  # either Namespaced or Cluster
  scope: Cluster
  names:
    plural: keycloakusers
    singular: keycloakuser
    kind: KeycloakUser
    shortNames:
    - kcusr
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
