apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-realm-operator-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: managed-keycloak-realm-operator
      automountServiceAccountToken: true
      containers:
      - name: operator
        image: {{ .Values.operatorImage }}
        ports:
          - containerPort: 12345  # debugger
        env:
          - name: KEYCLOAK_URL
            value: {{ .Values.keycloak.url }}
          - name: KEYCLOAK_USERNAME
            {{- toYaml $.Values.keycloak.username | nindent 12 }}
          - name: KEYCLOAK_PASSWORD
            {{- toYaml $.Values.keycloak.password | nindent 12 }}
          - name: REDIS_CONNECTION_STRING
            value: redis://operator-redis-svc:6379
          - name: DENO_CERT
            value: /kube-root-ca.crt
        resources: {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: kube-root-ca
          mountPath: /kube-root-ca.crt
          subPath: ca.crt
      volumes:
        - name: kube-root-ca
          configMap:
            name: kube-root-ca.crt